package application;

//import javafx.fxml.FXML;
//
//import javafx.scene.control.Button;
//
//import javafx.scene.control.TextField;
//
//import javafx.event.ActionEvent;
//
//public class ProgramStateController {
//	@FXML
//	private Button mybutton;
//	@FXML
//	private TextField myTextField;
//
//	// Event Listener on Button[#mybutton].onAction
//	@FXML
//	public void showDateTime(ActionEvent event) {
//		// TODO Autogenerated
//	}
//}
import java.awt.event.MouseEvent;
import java.net.URL;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.ResourceBundle;

import Model.Expression.ConstExp;
import Model.Expression.ReadHeapExp;
import Model.Expression.VarExp;
import Model.PrgState;
import Model.Statement.*;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.ListView;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

public class ProgramsController implements Initializable {

    @FXML
    private ListView<IStatement> programsList;

    public ProgramsController() {

    }

    @Override
    public void initialize(URL location, ResourceBundle resources) {

        IStatement exp = new CompStatement(new OpenFileStatement("g", "src/fisier.out"), new CompStatement(new AssgnStatement("v", new ConstExp(10)),
                new CompStatement(new CompStatement(new NewHeapValueStatement("a", new ConstExp(22)),
                        new ForkStatement(new ForkStatement(
                                new CompStatement(new WriteHeapStatement("a", new ConstExp(30)), new CompStatement(new AssgnStatement("v", new ConstExp(32)),
                                        new CompStatement(new PrintStatement(new VarExp("v")), new PrintStatement(new ReadHeapExp("a"))))))
                        )), new CompStatement(new PrintStatement(new VarExp("v")), new PrintStatement(new ReadHeapExp("a"))))));

        ObservableList<IStatement> items = FXCollections.observableArrayList(exp,
                                                                 exp,
                                                                 exp);
        programsList.setItems(items);
        programsList.setOnMouseClicked(new EventHandler<javafx.scene.input.MouseEvent>() {
            @Override
            public void handle(javafx.scene.input.MouseEvent mouseEvent) {
//                System.out.println("clicked on " + programsList.getSelectionModel().getSelectedItem());
                Stage menuStage = new Stage();
                ProgramState menu = new ProgramState(programsList.getSelectionModel().getSelectedItem());
                menu.start(menuStage);
                menuStage.show();
            }
        });

    }
}